apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-wil
spec:
    replicas: 2
    selector:
        matchLabels:
            app: app-wil
    template:
        metadata:
            labels:
                app: app-wil
        spec:
            containers:
            - name: app-wil
              image: wil42/playground:v2
              ports:
              - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
    name: app-wil
spec:
    ports:
    - name: http
      port: 8888
      targetPort: 8888
    selector:
        app: app-wil
